Design-Document
Anvarka/RogueLike pull request #1
Opened 2021-04-04 21:51 UTC by Anvarka

2021-04-04 21:53 UTC, Anvarka commented
Здравствуйте, делали вместе с Димой Ивановым.

2021-04-14 14:57 UTC, aleksZubakov requested changes

2021-04-14 14:57 UTC, aleksZubakov commented on README.md
> +* Существуют объекты - магазины, в которых можно купить/продать предметы за золото
Это не нужно исправлять, но вообще длинные списки сложно читать обычно, мне кажется, что учше поинты объединять. Отдельно про персонажей, отдельно про противников и т.д. Потом легко будет вынести в отдельные вики-страницы, если разрастется документ

2021-04-14 14:57 UTC, aleksZubakov commented on README.md
> +![](https://github.com/Anvarka/RogueLike/blob/main/useCase.png)
Что-то не так со стрелочками, они обычно специально пунктиром рисуются, если что-то расширяет

Кажется, что можно не перечислять все действия, но ок. В остальном адекватно

2021-04-14 14:57 UTC, aleksZubakov commented on README.md
> +![](https://github.com/Anvarka/RogueLike/blob/main/components.png)
Странно, что в названиях компонент написаны действия. Напоминаю, что еще должно было быть:
> - Распределение компонентов между участниками команды
> - Уточнение компонентов диаграммами классов

2021-05-14 15:49 UTC, aleksZubakov commented
Не идеально, но ок засчитываю

2021-05-14 15:49 UTC, closed without merging