Basic game
Anvarka/RogueLike pull request #2
Opened 2021-04-19 03:49 UTC by Anvarka

2021-04-19 03:57 UTC, Anvarka commented
Делали вместе с Димой Ивановым.

2021-04-23 17:42 UTC, aleksZubakov requested changes
В целом, ок. Добавьте комментарии и тесты и исправьте мелочи, указанные ниже. Пока 8 из 10

2021-04-23 17:42 UTC, ottergottaott commented on RogueLike/server/views.py
> +        new_pos = [cur_x, cur_y - 1]
А почему не tuple, если мы точно знаем, что координаты всего 2?

2021-04-23 17:42 UTC, ottergottaott commented on RogueLike/server/views.py
> +    cur_x = player[0]
`cur_x, cur_y = player`

2021-04-23 17:42 UTC, aleksZubakov commented on RogueLike/server/views.py
> +        return HttpResponse("Error")
Для ошибок есть специальные респонсы, или хотя бы статус меняйте. Со списком статусов можно [тут ознакомиться ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

2021-04-23 17:42 UTC, aleksZubakov commented on RogueLike/server/views.py
> +            return obj.__dict__
Что-то явно грязное и вредное, не стоит в `__dict__` лезть руками

2021-04-23 17:42 UTC, aleksZubakov commented on RogueLike/server/views.py
> +    """
Какая-то совсем ленивая генерация получилась

2021-04-23 17:42 UTC, aleksZubakov commented on RogueLike/server/views.py
> +        user_and_map = models.User.objects.get(user_id=user_id)
А это нельзя проверить без try/catch?

2021-05-14 15:52 UTC, aleksZubakov commented
Кажется, тут ничего не исправили

2023-03-02 18:01 UTC, merged